--- !rabbit-tk/config
# menu_bg, menu_highlight, menu_highlight_text, font, fg_color
appearance:
    background: #aaaaaa
    text-color: #000000
    button-color: #ffffff
    menu-highlight: #5555aa
    highlight-text: #ffffff
    main-font:
        face: sans
        size: 10
