--- !rabbit-tk/config
# menu_bg, menu_highlight, menu_highlight_text, font, fg_color
appearance:
    background: "#555555"
    text-color: "#000000"
    menu-highlight: "#5555aa"
    highlight-text: "#000000"
